### ISSUE TITLE
 Implementar Templates de Issue

### ISSUE THREAD

**Issue by NaBuchholz** [Quest-Finder/temvagamestre.frontend#100]
**Descrição:**

Este issue propõe a criação de templates de issue para o repositório temvagamestre.frontend . Templates padronizarão as issues, facilitando a comunicação e organização.

**Benefícios:**

* Comunicação mais clara e eficiente.
* Maior organização do repositório.
* Aumento da produtividade.

**Proposta:**

- [x] Criar templates para diferentes tipos de issues (bugs, features, tarefas).
- [x] Incluir campos obrigatórios: título, descrição, rótulos e marcos.
- [x] Fornecer instruções claras para o preenchimento.
- [x] Tornar os templates facilmente acessíveis.
- [ ] Documentar na wiki do repositório.

**Comment by julianosill** [comment]
Apenas para registro do fechamento desta `Issue`:
Foram criadas páginas específicas na Wiki para cada template de `Issue` criadas.
