### ISSUE TITLE
Implementar Templates de Pull Request

### ISSUE THREAD

**Issue by NaBuchholz** [Quest-Finder/temvagamestre.frontend#101]
Descrição:

Este issue propõe a criação de templates de pull request para o repositório temvagamestre.frontend . Templates padronizarão os pull requests, facilitando a comunicação e organização.

**Benefícios**:

- Comunicação mais clara e eficiente.
- Maior organização do repositório.
- Aumento da produtividade.

**Proposta**:

- [x] Criar templates para diferentes tipos de issues (novas features, correções de bugs, refatorações).
- [x] Incluir campos obrigatórios: título, descrição, rótulos e marcos.
- [x] Fornecer instruções claras para o preenchimento.
- [x] Tornar os templates facilmente acessíveis.
- [ ] Documentar na wiki do repositório.

**Comment by julianosill** [comment]
Na parte de documentação da wiki, criei esta página: https://github.com/Quest-Finder/temvagamestre.frontend/wiki/Criando-uma-Pull-Request

Se estiver aprovada, podemos fechar essa issue.

**Comment by NaBuchholz** [comment]
@julianosill  quando você mergeia o pr que contém essa issue mensionada, ela fecha automaticamente. Para as próximas vezes :)

**Comment by julianosill** [comment]
Ah sim, eu vi a informação. Porém, quando o Emerson mergeou e fechou a PR, essa issue continuou aberta.
