### ISSUE TITLE
[BUG] Ao checkbox não funciona

### ISSUE THREAD

**Issue by emerson-oliveira** [Quest-Finder/temvagamestre.frontend#118]
E necessário clicar mais de uma vez para mudar o estado do componente checkbox da visiblidade.

https://temvagamestre.com/cadastro/redes-sociais
![image](https://github.com/user-attachments/assets/f4f7bc8f-e4cb-4a41-a3a9-407a920ad9fa)

**Comment by julianosill** [comment]
Uma observação, esse switcher de visibilidade será removido. Isso foi comentado em uma reunião passada.

Não há necessidade dele, iremos exibir as redes sociais que o usuário informar.
