### ISSUE TITLE
[Melhoria] Ajustar a fonte do projeto para deixar igual ao do figma

### ISSUE THREAD

**Issue by htamagnus** [Quest-Finder/temvagamestre.frontend#124]
A fonte do projeto é diferente do protótipo do figma. Aparentemente, onde era para ser Roboto está Noto Sans e vice-versa.

## Atual:
No titulo "Estilos preferidos" está com a fonte "Roboto" ":
![image](https://github.com/user-attachments/assets/73df095f-065a-4bb8-a2fd-bfdb32640383)

Na "bio" está com a fonte "NotoSans" : 
![image](https://github.com/user-attachments/assets/d9b0f8de-fd89-4883-8b36-8eefb3bd3cd3)

---

## Desejado:
No figma, no título "Estilos preferidos" está com a fonte "Noto Sans":
![image](https://github.com/user-attachments/assets/42c24cab-98e1-4bef-98b1-3ae3f0f3681f)
![image](https://github.com/user-attachments/assets/5c0e130b-5ab9-4b69-8b81-a12f25282d35)

---

No figma, na bio, está com a fonte "Roboto":
![image](https://github.com/user-attachments/assets/67edc0ac-5774-40a1-ab55-7761f9f16588)

**Comment by MathMendesReis** [comment]
Vou ajustar
